### ISSUE TITLE
背景圆角

### ISSUE THREAD

**Issue by shichunlei** [JeasonWong/ElemeShoppingView#1]
为什么我运行完是这样的效果？

![screenshot_2016-07-14-09-32-00_me wangyuwei shopp](https://cloud.githubusercontent.com/assets/7146745/16825300/14b5d010-49a6-11e6-9f15-17b917a19892.png)

**Comment by JeasonWong** [comment]
麻烦留下系统版本？

**Comment by BarryWhy** [comment]
我的版本是4.4的，背景圆角也是这样

**Comment by shichunlei** [comment]
Android 4.4.2     代码导到eclipse运行的

**Comment by JeasonWong** [comment]
好的，我今天会把背景换种方式重写，稍等下

**Comment by JeasonWong** [comment]
@BarryWhy @shichunlei 已经修好了，**compile 'me.wangyuwei:shoppoing:1.0.2'**
谢谢你们的反馈~
