### ISSUE TITLE
在RecyclerView使用ShoppingClickListener不会拦截父控件的点击事件

### ISSUE THREAD

**Issue by 0xm1nam0** [JeasonWong/ElemeShoppingView#3]
在RecyclerView使用ShoppingClickListener不会拦截父控件的点击事件
触发ShoppingClickListener也会触发父控件的点击事件。

**Comment by 0xm1nam0** [comment]
onTouchEvent方法
 return true;
已解决

**Comment by JeasonWong** [comment]
I have fixed in 1.0.5. Please upgrade to 'me.wangyuwei:shoppoing:1.0.5' . Thx.  😁
